services:
  stt-server:
    image: ghcr.io/reevesl/stt_server:latest
    ports:
      - "8001:8000"
    environment:
      - HF_TOKEN=hf_xxxxxxxxxxxxxxxxxxxx
      - OMP_NUM_THREADS=12
      - MAX_WORKERS=2
      - ARCHIVE_PATH=/mnt/stt_files
      - RETENTION_DAYS=2
      - WEBHOOK_URL=
      - WEBHOOK_ENABLED=false
    volumes:
      - hf_cache:/root/.cache/huggingface
      - transcripts:/app/transcripts
      - /mnt/stor3/stt_files:/mnt/stt_files
    restart: unless-stopped

volumes:
  hf_cache:
  transcripts:
